### ISSUE TITLE
Add support for autorun files 

### ISSUE THREAD

**Issue by Rafiot** [CIRCL/PyCIRCLean#3]

**Comment by dputtick** [comment]
Since bin/filecheck.py is the most complete of the examples, I'll add autorun.inf support there

**Comment by dputtick** [comment]
Currently, filecheck.py considers files with a .inf extension malicious, and will automatically label them as dangerous. This should be enough to prevent older versions of windows from running them, right? We can also make it so they aren't copied to the destination directory at all to be extra safe.
